Map<String, String> exm = {};
Map<String, String> Search_Product = {};

// homescreen
const Map<String, String> bharatUdyog = {
  'Hindi': 'भारत उद्योग',
  'Bengali': 'ভারত উদ্যোগ',
  'Telugu': 'భారత్ ఉద్యోగ్',
  'Marathi': 'भारत उद्योग',
  'Tamil': 'பாரத் உத்யோகம்',
  'Urdu': 'بھارتی کاروبار',
  'Gujarati': 'ભારત ઉદ્યોગ',
  'Malayalam': 'ഭാരത് ഉദ്യോഗം',
  'Kannada': 'ಭಾರತ ಉದ್ಯೋಗ',
  'Odia': 'ଭାରତ ଉଦ୍ୟୋଗ',
  'Punjabi': 'ਭਾਰਤ ਉਦਯੋਗ',
  'Assamese': 'ভাৰত উদ্যোগ',
  'Nepali': 'भारत उद्योग',
  'English': 'Bharat Udyog',
  'Spanish': 'Industria bharat',
  'French': 'Industrie indienne',
  'German': 'Indische Industrie',
  'Italian': 'Industria Indiana',
  'Portuguese': 'Indústria indiana',
  'Russian': 'Индийская промышленность',
  'Chinese': '印度工业',
  'Japanese': 'インドの産業',
  'Korean': '인도 산업',
  'Turkish': 'Hint Sanayi',
  'Dutch': 'Indiase industrie',
  'Swedish': 'Indisk industri',
  'Norwegian': 'Indisk industri',
  'Finnish': 'Intialainen teollisuus',
  'Greek': 'Ινδική βιομηχανία',
  'Thai': 'อุตสาหกรรมอินเดีย',
};
const Map<String, String> fromIndianMarketsToYourDoorstep = {
  'Hindi': 'भारतीय बाजार से आपके द्वार तक',
  'Bengali': 'ভারতীয় বাজার থেকে আপনার পর্বতে',
  'Telugu': 'ఇండియన్ మార్కెట్స్ నుండి మీ ద్వారానికి',
  'Marathi': 'भारतीय मार्केट्समधून आपल्या द्वाराकडे',
  'Tamil': 'இந்திய சந்தைகளிலிருந்து உங்கள் தொலைவிக்கு',
  'Urdu': 'بھارتی مارکیٹس سے آپ کے دربست پر',
  'Gujarati': 'ભારતીય બજારો થી તમારા દરવાજા પર',
  'Malayalam': 'ഇന്ത്യൻ മാർക്കറ്റുകൾ നിങ്ങളുടെ അടുത്തിരിക്കുന്നു',
  'Kannada': 'ಭಾರತೀಯ ಮಾರುಕಟ್ಟೆಗಳಿಂದ ನಿಮ್ಮ ಬಾಗಿಲಿಗೆ',
  'Odia': 'ଭାରତୀୟ ମାର୍କେଟ୍‌ରୁ ଆପଣଙ୍କ ଦ୍ୱାରପଟେ',
  'Punjabi': 'ਭਾਰਤੀ ਮਾਰਕੀਟਸ ਤੋਂ ਤੁਹਾਡੇ ਦਰਵਾਜ਼ੇ ਤੱਕ',
  'Assamese': 'ভাৰতীয় বজাৰৰ পৰা আপোনাৰ দৰজালৈ',
  'Nepali': 'भारतीय बजारहरूबाट तपाईंको द्वारमा',
  'English': 'From Indian Markets to Your doorstep',
  'Spanish': 'De los mercados indios a tu puerta',
  'French': 'Des marchés indiens à votre porte',
  'German': 'Von indischen Märkten zu Ihrer Tür',
  'Italian': 'Dai mercati indiani alla tua porta',
  'Portuguese': 'Dos mercados indianos à sua porta',
  'Russian': 'Из индийских рынков к вашему порогу',
  'Chinese': '从印度市场到您的门前',
  'Japanese': 'インドの市場からあなたの玄関まで',
  'Korean': '인도 시장에서 당신의 문 앞까지',
  'Turkish': 'Hint pazarlarından kapınıza',
  'Dutch': 'Van Indiase markten naar jouw deur',
  'Swedish': 'Från indiska marknader till din dörr',
  'Norwegian': 'Fra indiske markeder til din dør',
  'Finnish': 'Intian markkinoilta kotiovellesi',
  'Greek': 'Από τις αγορές της Ινδίας στην πόρτα σας',
  'Thai': 'จากตลาดอินเดียถึงประตูบ้านคุณ',
};

const Map<String, String> dealsTranslations = {
  'Hindi': 'डील्स',
  'Bengali': 'ডিলস',
  'Telugu': 'డిల్స్',
  'Marathi': 'सौदे',
  'Tamil': 'பொருத்தம்',
  'Urdu': 'سودے',
  'Gujarati': 'ડીલ્સ',
  'Malayalam': 'ഡിലുകൾ',
  'Kannada': 'ಡಿಲ್ಸ್',
  'Odia': 'ଡିଲ୍ସ',
  'Punjabi': 'ਡੀਲਸ',
  'Assamese': 'ডিলচ',
  'Nepali': 'सम्झौता',
  'English': 'Deals',
  'Spanish': 'Ofertas',
  'French': 'Offres',
  'German': 'Angebote',
  'Italian': 'Offerte',
  'Portuguese': 'Ofertas',
  'Russian': 'Сделки',
  'Chinese': '交易',
  'Japanese': '取引',
  'Korean': '딜',
  'Turkish': 'Anlaşmalar',
  'Dutch': 'Deals',
  'Swedish': 'Erjudanden',
  'Norwegian': 'Avtaler',
  'Finnish': 'Sopimukset',
  'Greek': 'Συμφωνίες',
  'Thai': 'ดีล',
};

const Map<String, String> billTranslations = {
  'Hindi': 'बिल',
  'Bengali': 'বিল',
  'Telugu': 'బిల్',
  'Marathi': 'बिल',
  'Tamil': 'பில்',
  'Urdu': 'بل',
  'Gujarati': 'બિલ',
  'Malayalam': 'ബിൽ',
  'Kannada': 'ಬಿಲ್',
  'Odia': 'ବିଲ',
  'Punjabi': 'ਬਿੱਲ',
  'Assamese': 'বিল',
  'Nepali': 'बिल',
  'English': 'Bill',
  'Spanish': 'Factura',
  'French': 'Facture',
  'German': 'Rechnung',
  'Italian': 'Fattura',
  'Portuguese': 'Conta',
  'Russian': 'Счет',
  'Chinese': '账单',
  'Japanese': '請求書',
  'Korean': '계산서',
  'Turkish': 'Fatura',
  'Dutch': 'Rekening',
  'Swedish': 'Räkning',
  'Norwegian': 'Regning',
  'Finnish': 'Lasku',
  'Greek': 'Τιμολόγιο',
  'Thai': 'บิล',
};

const Map<String, String> artsTranslations = {
  'Hindi': 'कला',
  'Bengali': 'শিল্প',
  'Telugu': 'కళాలు',
  'Marathi': 'कला',
  'Tamil': 'கலைகள்',
  'Urdu': 'صنعت',
  'Gujarati': 'આર્ટ',
  'Malayalam': 'കലകൾ',
  'Kannada': 'ಕಲೆಗಳು',
  'Odia': 'କଳା',
  'Punjabi': 'ਕਲਾਵੰਤ',
  'Assamese': 'কলা',
  'Nepali': 'कला',
  'English': 'Arts',
  'Spanish': 'Artes',
  'French': 'Arts',
  'German': 'Kunst',
  'Italian': 'Arti',
  'Portuguese': 'Artes',
  'Russian': 'Искусство',
  'Chinese': '艺术',
  'Japanese': '芸術',
  'Korean': '예술',
  'Turkish': 'Sanat',
  'Dutch': 'Kunst',
  'Swedish': 'Konst',
  'Norwegian': 'Kunst',
  'Finnish': 'Taide',
  'Greek': 'Τέχνες',
  'Thai': 'ศิลปะ',
};

const Map<String, String> giftsTranslations = {
  'Hindi': 'उपहार',
  'Bengali': 'উপহার',
  'Telugu': 'ఉపోహారాలు',
  'Marathi': 'भेट',
  'Tamil': 'பரிசுகள்',
  'Urdu': 'تحفے',
  'Gujarati': 'ઉપહારો',
  'Malayalam': 'ഗിഫ്റ്റുകൾ',
  'Kannada': 'ಉಪಹಾರಗಳು',
  'Odia': 'ଉପହାର',
  'Punjabi': 'ਤੋਹਫ਼ੇ',
  'Assamese': 'উপহার',
  'Nepali': 'उपहार',
  'English': 'Gifts',
  'Spanish': 'Regalos',
  'French': 'Cadeaux',
  'German': 'Geschenke',
  'Italian': 'Regali',
  'Portuguese': 'Presentes',
  'Russian': 'Подарки',
  'Chinese': '礼物',
  'Japanese': '贈り物',
  'Korean': '선물',
  'Turkish': 'Hediyeler',
  'Dutch': 'Cadeaus',
  'Swedish': 'Presenter',
  'Norwegian': 'Gaver',
  'Finnish': 'lahjat',
  'Greek': 'Δώρα',
  'Thai': 'ของขวัญ',
};

const Map<String, String> moreTranslations = {
  'Hindi': 'अधिक',
  'Bengali': 'আরও',
  'Telugu': 'మరింత',
  'Marathi': 'अधिक',
  'Tamil': 'மேலும்',
  'Urdu': 'مزید',
  'Gujarati': 'વધુ',
  'Malayalam': 'കൂടുതൽ',
  'Kannada': 'ಹೆಚ್ಚು',
  'Odia': 'ଅଧିକ',
  'Punjabi': 'ਹੋਰ',
  'Assamese': 'অধিক',
  'Nepali': 'थप',
  'English': 'More',
  'Spanish': 'Más',
  'French': 'Plus',
  'German': 'Mehr',
  'Italian': 'Di più',
  'Portuguese': 'Mais',
  'Russian': 'Больше',
  'Chinese': '更多',
  'Japanese': 'もっと',
  'Korean': '더',
  'Turkish': 'Daha fazla',
  'Dutch': 'Meer',
  'Swedish': 'Mer',
  'Norwegian': 'Mer',
  'Finnish': 'Lisää',
  'Greek': 'Περισσότερο',
  'Thai': 'มากกว่า',
};

const Map<String, String> searchProductTranslations = {
  'Hindi': 'उत्पाद खोजें',
  'Bengali': 'পণ্য অনুসন্ধান',
  'Telugu': 'ఉత్పత్తి వెతకండి',
  'Marathi': 'उत्पादन शोधा',
  'Tamil': 'தயாரிப்பு தேடு',
  'Urdu': 'مصنوعات تلاش کریں',
  'Gujarati': 'ઉત્પાદન શોધો',
  'Malayalam': 'ഉത്പന്നം തിരയുക',
  'Kannada': 'ಉತ್ಪನ್ನ ಹುಡುಕಿ',
  'Odia': 'ପରିପରି ଖୋଜନ୍ତୁ',
  'Punjabi': 'ਉਤਪਾਦ ਖੋਜੋ',
  'Assamese': 'উৎপাদন সন্ধান কৰক',
  'Nepali': 'उत्पादन खोजी',
  'English': 'Search Product',
  'Spanish': 'Buscar Producto',
  'French': 'Rechercher un produit',
  'German': 'Produkt suchen',
  'Italian': 'Cerca Prodotto',
  'Portuguese': 'Buscar Produto',
  'Russian': 'Поиск продукта',
  'Chinese': '搜索产品',
  'Japanese': '製品を検索する',
  'Korean': '제품 검색',
  'Turkish': 'Ürün Ara',
  'Dutch': 'Product zoeken',
  'Swedish': 'Sök produkt',
  'Norwegian': 'Søk produkt',
  'Finnish': 'Etsi tuotetta',
  'Greek': 'Αναζήτηση προϊόντος',
  'Thai': 'ค้นหาสินค้า',
};

const Map<String, String> seeMoreTranslations = {
  'Hindi': 'और देखें',
  'Bengali': 'আরও দেখুন',
  'Telugu': 'మరింత చూడండి',
  'Marathi': 'अधिक पहा',
  'Tamil': 'மேலே காண்பி',
  'Urdu': 'مزید دیکھیں',
  'Gujarati': 'વધુ જુઓ',
  'Malayalam': 'കൂടുതൽ കാണുക',
  'Kannada': 'ಇನ್ನಷ್ಟು ನೋಡಿ',
  'Odia': 'ଆଉ ଦେଖନ୍ତୁ',
  'Punjabi': 'ਹੋਰ ਦੇਖੋ',
  'Assamese': 'অধিক চাওক',
  'Nepali': 'थप हेर्नुहोस्',
  'English': 'See More',
  'Spanish': 'Ver más',
  'French': 'Voir plus',
  'German': 'Mehr anzeigen',
  'Italian': 'Vedi altro',
  'Portuguese': 'Ver mais',
  'Russian': 'Смотреть больше',
  'Chinese': '查看更多',
  'Japanese': 'もっと見る',
  'Korean': '더 보기',
  'Turkish': 'Daha fazla görüntüle',
  'Dutch': 'Bekijk meer',
  'Swedish': 'Se mer',
  'Norwegian': 'Se mer',
  'Finnish': 'Näytä lisää',
  'Greek': 'Δείτε περισσότερα',
  'Thai': 'ดูเพิ่มเติม',
};

const Map<String, String> specialForYouTranslations = {
  'Hindi': 'आपके लिए विशेष',
  'Bengali': 'আপনার জন্য বিশেষ',
  'Telugu': 'మీ కోసం ప్రత్యేకం',
  'Marathi': 'तुमच्यासाठी विशेष',
  'Tamil': 'உங்களுக்கு சிறப்பு',
  'Urdu': 'آپ کے لیے خاص',
  'Gujarati': 'તમારા માટે વિશેષ',
  'Malayalam': 'നിങ്ങളുക്ക് പ്രത്യേകം',
  'Kannada': 'ನಿಮಗಾಗಿ ವಿಶೇಷ',
  'Odia': 'ଆପଣଙ୍କ ଜୋଡ଼ା ପାଇଁ ବିଶେଷ',
  'Punjabi': 'ਤੁਹਾਡੇ ਲਈ ਖਾਸ',
  'Assamese': 'আপোনাৰ বাবে বিশেষ',
  'Nepali': 'तपाईंको लागि विशेष',
  'English': 'Special for You',
  'Spanish': 'Especial para ti',
  'French': 'Spécial pour toi',
  'German': 'Speziell für dich',
  'Italian': 'Speciale per te',
  'Portuguese': 'Especial para você',
  'Russian': 'Особенное для вас',
  'Chinese': '特别为您',
  'Japanese': 'あなたのための特別',
  'Korean': '당신을 위한 특별한',
  'Turkish': 'Senin için özel',
  'Dutch': 'Speciaal voor jou',
  'Swedish': 'Speciellt för dig',
  'Norwegian': 'Spesielt for deg',
  'Finnish': 'Sinulle erityistä',
  'Greek': 'Ειδικό για σένα',
  'Thai': 'พิเศษสำหรับคุณ',
};

const Map<String, String> wallPaintingsTranslations = {
  'Hindi': 'दीवार चित्रकला',
  'Bengali': 'দেওয়াল চিত্রকলা',
  'Telugu': 'వాలు చిత్రకళాలు',
  'Marathi': 'दिवार चित्रकला',
  'Tamil': 'கீழ் வரையில் சித்திரகள்',
  'Urdu': 'دیواری نقاشیاں',
  'Gujarati': 'દીવાર ચિત્રકલા',
  'Malayalam': 'വീട്ടിലെ ചിത്രങ്ങൾ',
  'Kannada': 'ವಾಲ್ ಚಿತ್ರಕಲೆಗಳು',
  'Odia': 'ଦେଓଣ ଚିତ୍ରକଳା',
  'Punjabi': 'ਦੀਵਾਰ ਚਿੱਤਰਕਾਰੀ',
  'Assamese': 'দেওয়াল চিত্ৰকলা',
  'Nepali': 'दीवार चित्रकला',
  'English': 'Wall Paintings',
  'Spanish': 'Pinturas murales',
  'French': 'Peintures murales',
  'German': 'Wandgemälde',
  'Italian': 'Pitture murali',
  'Portuguese': 'Pinturas de parede',
  'Russian': 'Нарисованные стены',
  'Chinese': '壁画',
  'Japanese': '壁画',
  'Korean': '벽화',
  'Turkish': 'Duvar resimleri',
  'Dutch': 'Muurschilderingen',
  'Swedish': 'Väggmålningar',
  'Norwegian': 'Veggmalerier',
  'Finnish': 'Seinämaalaukset',
  'Greek': 'Τοιχογραφίες',
  'Thai': 'ภาพเขียนบนผนัง',
};

const Map<String, String> fashionTranslations = {
  'Hindi': 'फैशन',
  'Bengali': 'ফ্যাশন',
  'Telugu': 'ఫ్యాషన్',
  'Marathi': 'फॅशन',
  'Tamil': 'ஃபேஷன்',
  'Urdu': 'فیشن',
  'Gujarati': 'ફેશન',
  'Malayalam': 'ഫാഷൻ',
  'Kannada': 'ಫ್ಯಾಷನ್',
  'Odia': 'ଫ୍ୟାସନ୍',
  'Punjabi': 'ਫੈਸ਼ਨ',
  'Assamese': 'ফেচন',
  'Nepali': 'फेसन',
  'English': 'Fashion',
  'Spanish': 'Moda',
  'French': 'Mode',
  'German': 'Mode',
  'Italian': 'Moda',
  'Portuguese': 'Moda',
  'Russian': 'Мода',
  'Chinese': '时尚',
  'Japanese': 'ファッション',
  'Korean': '패션',
  'Turkish': 'Moda',
  'Dutch': 'Mode',
  'Swedish': 'Mode',
  'Norwegian': 'Mote',
  'Finnish': 'Muoti',
  'Greek': 'Μόδα',
  'Thai': 'แฟชั่น',
};

const Map<String, String> popularProductsTranslations = {
  'Hindi': 'लोकप्रिय उत्पाद',
  'Bengali': 'জনপ্রিয় পণ্য',
  'Telugu': 'జనప్రియ ఉత్పత్తులు',
  'Marathi': 'लोकप्रिय उत्पादने',
  'Tamil': 'பிரபலமான பொருட்கள்',
  'Urdu': 'مشہور مصنوعات',
  'Gujarati': 'પ્રખ્યાત ઉત્પાદો',
  'Malayalam': 'ജനപ്രിയമായ ഉത്പന്നങ്ങൾ',
  'Kannada': 'ಜನಪ್ರಿಯ ಉತ್ಪನ್ನಗಳು',
  'Odia': 'ଜନସମ୍ମାନୀ ପ୍ରସ୍ତୁତି',
  'Punjabi': 'ਲੋਕਪ੍ਰਿਯ ਉਤਪਾਦਾਂ',
  'Assamese': 'জনপ্ৰিয় উৎপাদন',
  'Nepali': 'लोकप्रिय उत्पादनहरू',
  'English': 'Popular Products',
  'Spanish': 'Productos Populares',
  'French': 'Produits Populaires',
  'German': 'Beliebte Produkte',
  'Italian': 'Prodotti Popolari',
  'Portuguese': 'Produtos Populares',
  'Russian': 'Популярные товары',
  'Chinese': '热门产品',
  'Japanese': '人気商品',
  'Korean': '인기 제품',
  'Turkish': 'Popüler Ürünler',
  'Dutch': 'Populaire Producten',
  'Swedish': 'Populära Produkter',
  'Norwegian': 'Populære Produkter',
  'Finnish': 'Suositut Tuotteet',
  'Greek': 'Δημοφιλή Προϊόντα',
  'Thai': 'สินค้ายอดนิยม',
};

const Map<String, String> recommendForYouTranslations = {
  'Hindi': 'आपके लिए सिफारिशें',
  'Bengali': 'আপনার জন্য সুপারিশ',
  'Telugu': 'మీకు సిఫార్సులు',
  'Marathi': 'तुमच्यासाठी शिफारसी',
  'Tamil': 'உங்களுக்கான பரிந்துரைகள்',
  'Urdu': 'آپ کے لیے سفارشات',
  'Gujarati': 'તમારા માટે ભલામણો',
  'Malayalam': 'നിങ്ങൾക്കായി ശുപാർശകൾ',
  'Kannada': 'ನಿಮಗೆ ಶಿಫಾರಸುಗಳು',
  'Odia': 'ଆପଣଙ୍କ ପାଇଁ ସିଫାରିସ୍',
  'Punjabi': 'ਤੁਹਾਡੇ ਲਈ ਸਿਫਾਰਸ਼ਾਂ',
  'Assamese': 'আপোনাৰ বাবে সুপারিশ',
  'Nepali': 'तपाईंको लागि सिफारिसहरू',
  'English': 'Recommend for You',
  'Spanish': 'Recomendado para Ti',
  'French': 'Recommandé pour Vous',
  'German': 'Empfohlen für Sie',
  'Italian': 'Consigliato per Te',
  'Portuguese': 'Recomendado para Você',
  'Russian': 'Рекомендовано для вас',
  'Chinese': '为您推荐',
  'Japanese': 'あなたにおすすめ',
  'Korean': '당신을 위한 추천',
  'Turkish': 'Sizin İçin Öneriler',
  'Dutch': 'Aanbevolen voor Jou',
  'Swedish': 'Rekommenderat för Dig',
  'Norwegian': 'Anbefalt for Deg',
  'Finnish': 'Suositeltu Sinulle',
  'Greek': 'Προτεινόμενο για Εσάς',
  'Thai': 'แนะนำสำหรับคุณ',
};

const Map<String, String> festivalSpecificProductTranslations = {
  'Hindi': 'त्योहार-विशिष्ट उत्पाद',
  'Bengali': 'উৎসব-নির্দিষ্ট পণ্য',
  'Telugu': 'పండగ-సంబంధిత ఉత్పత్తి',
  'Marathi': 'सण-विशिष्ट उत्पादने',
  'Tamil': 'திருவிழா-சிறப்புப் பொருள்',
  'Urdu': 'تہوار کے مخصوص مصنوعات',
  'Gujarati': 'ઉત્સવ-વિશિષ્ટ ઉત્પાદન',
  'Malayalam': 'പെരുന്നാൾ-നിർദ്ദേശിത ഉൽപ്പന്നം',
  'Kannada': 'ಹಬ್ಬ-ನಿರ್ದಿಷ್ಟ ಉತ್ಪನ್ನ',
  'Odia': 'ପର୍ବ-ବିଶେଷ ପ୍ରସ୍ତୁତି',
  'Punjabi': 'ਤਿਉਹਾਰ-ਵਿਸ਼ੇਸ਼ ਉਤਪਾਦ',
  'Assamese': 'পৰ্বৰ-নিৰ্দিষ্ট সামগ্ৰী',
  'Nepali': 'चाडपर्व-विशेष उत्पादन',
  'English': 'Festival Specific Products',
  'Spanish': 'Producto Específico del Festival',
  'French': 'Produit Spécifique au Festival',
  'German': 'Festival-Spezifisches Produkt',
  'Italian': 'Prodotto Specifico per il Festival',
  'Portuguese': 'Produto Específico para o Festival',
  'Russian': 'Продукт, специфичный для фестиваля',
  'Chinese': '节日特定产品',
  'Japanese': 'フェスティバル特有の商品',
  'Korean': '축제 특화 제품',
  'Turkish': 'Festival Özel Ürünü',
  'Dutch': 'Festival-specifiek Product',
  'Swedish': 'Festivalsspecifik Produkt',
  'Norwegian': 'Festivalspecifikt Produkt',
  'Finnish': 'Festivaalikohtainen Tuote',
  'Greek': 'Προϊόν Ειδικό για Φεστιβάλ',
  'Thai': 'สินค้าที่เฉพาะเจาะจงสำหรับเทศกาล',
};

const Map<String, String> brandsTranslations = {
  'Hindi': 'ब्रांड्स',
  'Bengali': 'ব্র্যান্ড',
  'Telugu': 'బ్రాండ్స్',
  'Marathi': 'ब्रँड्स',
  'Tamil': 'பிராண்ட்ஸ்',
  'Urdu': 'برانڈز',
  'Gujarati': 'બ્રાંડ્સ',
  'Malayalam': 'ബ്രാൻഡുകൾ',
  'Kannada': 'ಬ್ರಾಂಡ್ಸ್',
  'Odia': 'ବ୍ରାଣ୍ଡ',
  'Punjabi': 'ਬ੍ਰਾਂਡ',
  'Assamese': 'ব্ৰাণ্ড',
  'Nepali': 'ब्राण्डहरू',
  'English': 'Brands',
  'Spanish': 'Marcas',
  'French': 'Marques',
  'German': 'Marken',
  'Italian': 'Marchi',
  'Portuguese': 'Marcas',
  'Russian': 'Бренды',
  'Chinese': '品牌',
  'Japanese': 'ブランド',
  'Korean': '브랜드',
  'Turkish': 'Markalar',
  'Dutch': 'Merken',
  'Swedish': 'Varumärken',
  'Norwegian': 'Merker',
  'Finnish': 'Brändit',
  'Greek': 'Μάρκες',
  'Thai': 'แบรนด์',
};

// wishlist

const Map<String, String> wishlistTranslations = {
  'Hindi': 'इच्छा-सूची',
  'Bengali': 'ইচ্ছা তালিকা',
  'Telugu': 'కోరికల జాబితా',
  'Marathi': 'इच्छा सूची',
  'Tamil': 'விருப்பங்கள் பட்டியல்',
  'Urdu': 'خواہش فہرست',
  'Gujarati': 'ઈચ્છાઓ યાદી',
  'Malayalam': 'പ്രിയങ്കരങ്ങൾ',
  'Kannada': 'ಇಚ್ಛಾಪಟ್ಟಿ',
  'Odia': 'ଇଚ୍ଛା ତାଲିକା',
  'Punjabi': 'ਇੱਛਾ-ਸੂਚੀ',
  'Assamese': 'ইচ্ছা তালিকা',
  'Nepali': 'इच्छा सूची',
  'English': 'Wishlist',
  'Spanish': 'Lista de deseos',
  'French': 'Liste de souhaits',
  'German': 'Wunschliste',
  'Italian': 'Lista dei desideri',
  'Portuguese': 'Lista de desejos',
  'Russian': 'Список желаемого',
  'Chinese': '心愿单',
  'Japanese': 'ほしい物リスト',
  'Korean': '찜한 목록',
  'Turkish': 'İstek listesi',
  'Dutch': 'Verlanglijstje',
  'Swedish': 'Önskelista',
  'Norwegian': 'Ønskeliste',
  'Finnish': 'Toivelista',
  'Greek': 'Λίστα επιθυμιών',
  'Thai': 'รายการสิ่งที่ต้องการ',
};

const Map<String, String> noProductsInWishlistTranslations = {
  'Hindi': 'विशिष्ट सूची में कोई उत्पाद नहीं है',
  'Bengali': 'ইচ্ছামতৃতার তালিকায় কোনো পণ্য নেই',
  'Telugu': 'విశేష జాబితాలో ఏ ఉత్పత్తులు లేవు',
  'Marathi': 'विशिष्ट सूचीत कोणतेही उत्पादनाही',
  'Tamil': 'விருப்பங்கள் பட்டியில் உருப்படிகள் இல்லை',
  'Urdu': 'وش لسٹ میں کوئی مصنوعات نہیں ہیں',
  'Gujarati': 'વિશેષ યાદવતમાં કોઈ ઉત્પાદનીઓ નથી',
  'Malayalam': 'ഇഷ്ടപ്പെട്ട പട്ടികയില്‍ പണം ഇല്ല',
  'Kannada': 'ಇಚ್ಛಾಪಟ್ಟಿಯಲ್ಲಿ ಯಾವುದೇ ಉತ್ಪನ್ನಗಳಿಲ್ಲ',
  'Odia': 'କୋନେଇ ଇଚ୍ଛା ତାଲିକାରେ ପ୍ରଡକ୍ଟ୍‌ ନାହିଁ',
  'Punjabi': 'ਕੋਈ ਪ੍ਰੋਡਕਟ ਵਿਸ਼ਲਿਸਟ ਵਿੱਚ ਨਹੀਂ ਹੈ',
  'Assamese': 'ইচ্ছা তালিকাত কোনো প্ৰডাক্ট নাই',
  'Nepali': 'इच्छा सूचिमा कुनै पनि उत्पादनहरू छैनन्',
  'English': 'No products in wishlist',
  'Spanish': 'No hay productos en la lista de deseos',
  'French': 'Aucun produit dans la liste de souhaits',
  'German': 'Keine Produkte auf der Wunschliste',
  'Italian': 'Nessun prodotto nella lista dei desideri',
  'Portuguese': 'Nenhum produto na lista de desejos',
  'Russian': 'Нет товаров в списке желаемого',
  'Chinese': '愿望清单中没有商品',
  'Japanese': 'ウィッシュリストに商品はありません',
  'Korean': '위시리스트에 제품이 없습니다',
  'Turkish': 'İstek listesinde ürün yok',
  'Dutch': 'Geen producten op de verlanglijst',
  'Swedish': 'Inga produkter på önskelistan',
  'Norwegian': 'Ingen produkter i ønskelisten',
  'Finnish': 'Ei tuotteita toiveluettelossa',
  'Greek': 'Δεν υπάρχουν προϊόντα στη λίστα επιθυμιών',
  'Thai': 'ไม่มีสินค้าในรายการสิ่งที่ต้องการ',
};

// allchating screeen
const Map<String, String> connectToExportersTranslations = {
  'Hindi': 'निर्यातकारियों से जुड़ें',
  'Bengali': 'রপ্তানিকারকদের সাথে যোগাযোগ করুন',
  'Telugu': 'ఎగుమతుల తో కనెక్ట్ అవుట్ చేయండి',
  'Marathi': 'निर्यातकार्यांस जोडा',
  'Tamil': 'ஏற்றுதல் செய்யுங்கள்',
  'Urdu': 'برآمد کاروں سے منسلک ہوں',
  'Gujarati': 'નિર્યાતકો સાથે જોડાઓ',
  'Malayalam': 'പൊരുതലുകൾ ചെയ്യുക',
  'Kannada': 'ರಫ್ತುದಾರರಿಗೆ ಸಂಪರ್ಕಿಸಿ',
  'Odia': 'ରପ୍ତାନୀକାରଙ୍କୁ ଯୋଗାଯୋଗ କରନ୍ତୁ',
  'Punjabi': 'ਨਿਰਯਾਤੀਆਂ ਨਾਲ ਜੁੜੋ',
  'Assamese': 'রপ্তানিকাৰী সম্পৰ্ক কৰক',
  'Nepali': 'निर्यातकर्ताहरूसँग जडान गर्नुहोस्',
  'English': 'Connect to Exporters',
  'Spanish': 'Conéctese con exportadores',
  'French': 'Se connecter aux exportateurs',
  'German': 'Verbindung zu Exporteuren herstellen',
  'Italian': 'Collegati agli esportatori',
  'Portuguese': 'Conectar-se aos exportadores',
  'Russian': 'Подключиться к экспортерам',
  'Chinese': '连接到出口商',
  'Japanese': '輸出業者に接続',
  'Korean': '수출업체에 연결',
  'Turkish': 'İhracatçılara Bağlan',
  'Dutch': 'Verbinden met exporteurs',
  'Swedish': 'Anslut till exportörer',
  'Norwegian': 'Koble til eksportører',
  'Finnish': 'Yhdistä viejiin',
  'Greek': 'Συνδεθείτε με εξαγωγείς',
  'Thai': 'เชื่อมต่อกับผู้ส่งออก',
};

// profile screen

const Map<String, String> myAccountTranslations = {
  'Hindi': 'मेरा खाता',
  'Bengali': 'আমার অ্যাকাউন্ট',
  'Telugu': 'నా ఖాతా',
  'Marathi': 'माझे खाते',
  'Tamil': 'என் கணக்கு',
  'Urdu': 'میرا اکاؤنٹ',
  'Gujarati': 'મારું એકાઉન્ટ',
  'Malayalam': 'എന്റെ അക്കൗണ്ട്',
  'Kannada': 'ನನ್ನ ಖಾತೆ',
  'Odia': 'ମୋ ଖାତା',
  'Punjabi': 'ਮੇਰਾ ਖਾਤਾ',
  'Assamese': 'মোৰ একাউণ্ট',
  'Nepali': 'मेरो खाता',
  'English': 'My Account',
  'Spanish': 'Mi cuenta',
  'French': 'Mon compte',
  'German': 'Mein Konto',
  'Italian': 'Il mio account',
  'Portuguese': 'Minha conta',
  'Russian': 'Мой аккаунт',
  'Chinese': '我的账户',
  'Japanese': 'マイアカウント',
  'Korean': '내 계정',
  'Turkish': 'Hesabım',
  'Dutch': 'Mijn account',
  'Swedish': 'Mitt konto',
  'Norwegian': 'Min konto',
  'Finnish': 'Tilini',
  'Greek': 'Ο λογαριασμός μου',
  'Thai': 'บัญชีของฉัน',
};

const Map<String, String> myOrdersTranslations = {
  'Hindi': 'मेरे आदेश',
  'Bengali': 'আমার অর্ডার',
  'Telugu': 'నా ఆర్డర్లు',
  'Marathi': 'माझे ऑर्डर्स',
  'Tamil': 'எனது ஆர்டர்கள்',
  'Urdu': 'میرے آرڈرز',
  'Gujarati': 'મારા આર્ડર્સ',
  'Malayalam': 'എന്റെ ഓർഡർകൾ',
  'Kannada': 'ನನ್ನ ಆರ್ಡರ್ಗಳು',
  'Odia': 'ମୋ ଅର୍ଡରଗୁଡ଼ିକ',
  'Punjabi': 'ਮੇਰੇ ਆਰਡਰ',
  'Assamese': 'মোৰ আৰ্ডাৰসমূহ',
  'Nepali': 'मेरो आदेशहरू',
  'English': 'My Orders',
  'Spanish': 'Mis pedidos',
  'French': 'Mes commandes',
  'German': 'Meine Bestellungen',
  'Italian': 'I miei ordini',
  'Portuguese': 'Meus pedidos',
  'Russian': 'Мои заказы',
  'Chinese': '我的订单',
  'Japanese': '私の注文',
  'Korean': '나의 주문',
  'Turkish': 'Benim Siparişlerim',
  'Dutch': 'Mijn bestellingen',
  'Swedish': 'Mina beställningar',
  'Norwegian': 'Mine bestillinger',
  'Finnish': 'Tilaukseni',
  'Greek': 'Οι παραγγελίες μου',
  'Thai': 'คำสั่งซื้อของฉัน',
};

const Map<String, String> settingsTranslations = {
  'Hindi': 'सेटिंग्स',
  'Bengali': 'সেটিংস',
  'Telugu': 'సెట్టింగ్స్',
  'Marathi': 'सेटिंग्ज',
  'Tamil': 'அமைப்புகள்',
  'Urdu': 'ترتیبات',
  'Gujarati': 'સેટિંગ્સ',
  'Malayalam': 'ക്രമീകരണങ്ങൾ',
  'Kannada': 'ಸೆಟ್ಟಿಂಗ್ಗಳು',
  'Odia': 'ସେଟିଂସ୍ |',
  'Punjabi': 'ਸੈਟਿੰਗਜ਼',
  'Assamese': 'ছেটিংছ',
  'Nepali': 'सेटिंग्स',
  'English': 'Settings',
  'Spanish': 'Ajustes',
  'French': 'Paramètres',
  'German': 'Einstellungen',
  'Italian': 'Impostazioni',
  'Portuguese': 'Configurações',
  'Russian': 'Настройки',
  'Chinese': '设置',
  'Japanese': '設定',
  'Korean': '설정',
  'Turkish': 'Ayarlar',
  'Dutch': 'Instellingen',
  'Swedish': 'Inställningar',
  'Norwegian': 'Innstillinger',
  'Finnish': 'Asetukset',
  'Greek': 'Ρυθμίσεις',
  'Thai': 'การตั้งค่า',
};

const Map<String, String> helpCenterTranslations = {
  'Hindi': 'सहायता केंद्र',
  'Bengali': 'সাহায্য কেন্দ্র',
  'Telugu': 'సహాయం కేంద్రం',
  'Marathi': 'सहाय्य केंद्र',
  'Tamil': 'உதவி மையம்',
  'Urdu': 'مدد مرکز',
  'Gujarati': 'સહાય કેન્દ્ર',
  'Malayalam': 'സഹായ കേന്ദ്രം',
  'Kannada': 'ಸಹಾಯ ಕೇಂದ್ರ',
  'Odia': 'ସହାୟତା କେନ୍ଦ୍ର',
  'Punjabi': 'ਸਹਾਇਤਾ ਕੇਂਦਰ',
  'Assamese': 'সাহায্য কেন্দ্ৰ',
  'Nepali': 'सहायता केन्द्र',
  'English': 'Help Center',
  'Spanish': 'Centro de ayuda',
  'French': 'Centre d’aide',
  'German': 'Hilfezentrum',
  'Italian': 'Centro assistenza',
  'Portuguese': 'Centro de ajuda',
  'Russian': 'Центр помощи',
  'Chinese': '帮助中心',
  'Japanese': 'ヘルプセンター',
  'Korean': '도움말 센터',
  'Turkish': 'Yardım Merkezi',
  'Dutch': 'Helpcentrum',
  'Swedish': 'Hjälpcenter',
  'Norwegian': 'Hjelpesenter',
  'Finnish': 'Apukeskus',
  'Greek': 'Κέντρο βοήθειας',
  'Thai': 'ศูนย์ช่วยเหลือ',
};

const Map<String, String> logoutTranslations = {
  'Hindi': 'लोग आउट',
  'Bengali': 'লগ আউট',
  'Telugu': 'లాగ్ అవుట్',
  'Marathi': 'लॉग आउट',
  'Tamil': 'வெளியேறு',
  'Urdu': 'لاگ آوٹ',
  'Gujarati': 'લોગ આઉટ',
  'Malayalam': 'ലോഗൗട്ട്',
  'Kannada': 'ಲಾಗ್ ಔಟ್',
  'Odia': 'ଲଗ୍ ଆଉଟ୍',
  'Punjabi': 'ਲੌਗ ਆਊਟ',
  'Assamese': 'লগ আউট',
  'Nepali': 'लग आउट',
  'English': 'Log out',
  'Spanish': 'Cerrar sesión',
  'French': 'Se déconnecter',
  'German': 'Ausloggen',
  'Italian': 'Disconnettersi',
  'Portuguese': 'Sair',
  'Russian': 'Выйти',
  'Chinese': '登出',
  'Japanese': 'ログアウト',
  'Korean': '로그아웃',
  'Turkish': 'Çıkış yap',
  'Dutch': 'Uitloggen',
  'Swedish': 'Logga ut',
  'Norwegian': 'Logg ut',
  'Finnish': 'Kirjaudu ulos',
  'Greek': 'Αποσύνδεση',
  'Thai': 'ออกจากระบบ',
};

// profile / my acccount

const Map<String, String> nameTranslations = {
  'Hindi': 'नाम',
  'Bengali': 'নাম',
  'Telugu': 'పేరు',
  'Marathi': 'नाव',
  'Tamil': 'பெயர்',
  'Urdu': 'نام',
  'Gujarati': 'નામ',
  'Malayalam': 'പേര്',
  'Kannada': 'ಹೆಸರು',
  'Odia': 'ନାଁ',
  'Punjabi': 'ਨਾਂ',
  'Assamese': 'নাম',
  'Nepali': 'नाम',
  'English': 'Name',
  'Spanish': 'Nombre',
  'French': 'Nom',
  'German': 'Name',
  'Italian': 'Nome',
  'Portuguese': 'Nome',
  'Russian': 'Имя',
  'Chinese': '名字',
  'Japanese': '名前',
  'Korean': '이름',
  'Turkish': 'Ad',
  'Dutch': 'Naam',
  'Swedish': 'Namn',
  'Norwegian': 'Navn',
  'Finnish': 'Nimi',
  'Greek': 'Όνομα',
  'Thai': 'ชื่อ',
};

const Map<String, String> emailTranslations = {
  'Hindi': 'ईमेल',
  'Bengali': 'ইমেল',
  'Telugu': 'ఇమెయిల్',
  'Marathi': 'ईमेल',
  'Tamil': 'மின்னஞ்சல்',
  'Urdu': 'ای میل',
  'Gujarati': 'ઇમેઇલ',
  'Malayalam': 'ഇമെയിൽ',
  'Kannada': 'ಇಮೇಲ್',
  'Odia': 'ଇମେଲ',
  'Punjabi': 'ਈਮੇਲ',
  'Assamese': 'ইমেইল',
  'Nepali': 'इमेल',
  'English': 'Email',
  'Spanish': 'Correo electrónico',
  'French': 'Email',
  'German': 'E-Mail',
  'Italian': 'Email',
  'Portuguese': 'Email',
  'Russian': 'Электронная почта',
  'Chinese': '电子邮件',
  'Japanese': 'メール',
  'Korean': '이메일',
  'Turkish': 'E-posta',
  'Dutch': 'E-mail',
  'Swedish': 'E-post',
  'Norwegian': 'E-post',
  'Finnish': 'Sähköposti',
  'Greek': 'Ηλεκτρονικό ταχυδρομείο',
  'Thai': 'อีเมล',
};

const Map<String, String> mobileNumberTranslations = {
  'Hindi': 'मोबाइल नंबर',
  'Bengali': 'মোবাইল নম্বর',
  'Telugu': 'మొబైల్ నంబర్',
  'Marathi': 'मोबाइल नंबर',
  'Tamil': 'கைபேசி எண்',
  'Urdu': 'موبائل نمبر',
  'Gujarati': 'મોબાઇલ નંબર',
  'Malayalam': 'മൊബൈൽ നമ്പർ',
  'Kannada': 'ಮೊಬೈಲ್ ಸಂಖ್ಯೆ',
  'Odia': 'ମୋବାଇଲ୍ ନମ୍ବର',
  'Punjabi': 'ਮੋਬਾਇਲ ਨੰਬਰ',
  'Assamese': 'মোবাইল নম্বৰ',
  'Nepali': 'मोबाइल नम्बर',
  'English': 'Mobile No.',
  'Spanish': 'Número de móvil',
  'French': 'Numéro de portable',
  'German': 'Handynummer',
  'Italian': 'Numero di cellulare',
  'Portuguese': 'Número de celular',
  'Russian': 'Номер мобильного',
  'Chinese': '手机号码',
  'Japanese': '携帯電話番号',
  'Korean': '휴대전화 번호',
  'Turkish': 'Cep Telefon Numarası',
  'Dutch': 'Mobiel nummer',
  'Swedish': 'Mobilnummer',
  'Norwegian': 'Mobilnummer',
  'Finnish': 'Matkapuhelinnumero',
  'Greek': 'Αριθμός κινητού τηλεφώνου',
  'Thai': 'หมายเลขโทรศัพท์มือถือ',
};

const Map<String, String> cityTranslations = {
  'Hindi': 'शहर',
  'Bengali': 'শহর',
  'Telugu': 'నగరం',
  'Marathi': 'शहर',
  'Tamil': 'நகரம்',
  'Urdu': 'شہر',
  'Gujarati': 'શહેર',
  'Malayalam': 'നഗരം',
  'Kannada': 'ನಗರ',
  'Odia': 'ସହର',
  'Punjabi': 'ਸ਼ਹਿਰ',
  'Assamese': 'চহৰ',
  'Nepali': 'शहर',
  'English': 'City',
  'Spanish': 'Ciudad',
  'French': 'Ville',
  'German': 'Stadt',
  'Italian': 'Città',
  'Portuguese': 'Cidade',
  'Russian': 'Город',
  'Chinese': '城市',
  'Japanese': '市',
  'Korean': '도시',
  'Turkish': 'Şehir',
  'Dutch': 'Stad',
  'Swedish': 'Stad',
  'Norwegian': 'By',
  'Finnish': 'Kaupunki',
  'Greek': 'Πόλη',
  'Thai': 'เมือง',
};

const Map<String, String> stateTranslations = {
  'Hindi': 'राज्य',
  'Bengali': 'রাজ্য',
  'Telugu': 'రాష్ట్రం',
  'Marathi': 'राज्य',
  'Tamil': 'மாநிலம்',
  'Urdu': 'ریاست',
  'Gujarati': 'રાજ્ય',
  'Malayalam': 'സംസ്ഥാനം',
  'Kannada': 'ಸಂಸ್ಥಾನ',
  'Odia': 'ରାଜ୍ୟ',
  'Punjabi': 'ਰਾਜ',
  'Assamese': 'ৰাজ্য',
  'Nepali': 'राज्य',
  'English': 'State',
  'Spanish': 'Estado',
  'French': 'État',
  'German': 'Bundesland',
  'Italian': 'Stato',
  'Portuguese': 'Estado',
  'Russian': 'Штат',
  'Chinese': '州',
  'Japanese': '州',
  'Korean': '주',
  'Turkish': 'Eyalet',
  'Dutch': 'Staat',
  'Swedish': 'Stat',
  'Norwegian': 'Stat',
  'Finnish': 'Osavaltio',
  'Greek': 'Πολιτεία',
  'Thai': 'รัฐ',
};

const Map<String, String> countryTranslations = {
  'Hindi': 'देश',
  'Bengali': 'দেশ',
  'Telugu': 'దేశం',
  'Marathi': 'देश',
  'Tamil': 'நாடு',
  'Urdu': 'ملک',
  'Gujarati': 'દેશ',
  'Malayalam': 'രാജ്യം',
  'Kannada': 'ದೇಶ',
  'Odia': 'ଦେଶ',
  'Punjabi': 'ਦੇਸ਼',
  'Assamese': 'দেশ',
  'Nepali': 'देश',
  'English': 'Country',
  'Spanish': 'País',
  'French': 'Pays',
  'German': 'Land',
  'Italian': 'Paese',
  'Portuguese': 'País',
  'Russian': 'Страна',
  'Chinese': '国家',
  'Japanese': '国',
  'Korean': '나라',
  'Turkish': 'Ülke',
  'Dutch': 'Land',
  'Swedish': 'Land',
  'Norwegian': 'Land',
  'Finnish': 'Maa',
  'Greek': 'Χώρα',
  'Thai': 'ประเทศ',
};
const Map<String, String> pincodeTranslations = {
  'Hindi': 'पिनकोड',
  'Bengali': 'পিনকোড',
  'Telugu': 'పిన్ కోడ్',
  'Marathi': 'पिनकोड',
  'Tamil': 'அஞ்சல் குறியீடு',
  'Urdu': 'پن کوڈ',
  'Gujarati': 'પિન કોડ',
  'Malayalam': 'പിൻ‌കോഡ്',
  'Kannada': 'ಪಿನ್ ಕೋಡ್',
  'Odia': 'ପିନ୍‌କୋଡ୍',
  'Punjabi': 'ਪਿੰਕੋਡ',
  'Assamese': 'পিনকোড',
  'Nepali': 'पिनकोड',
  'English': 'Pincode',
  'Spanish': 'Código postal',
  'French': 'Code postal',
  'German': 'Postleitzahl',
  'Italian': 'Codice postale',
  'Portuguese': 'Código postal',
  'Russian': 'Почтовый индекс',
  'Chinese': '邮政编码',
  'Japanese': '郵便番号',
  'Korean': '우편번호',
  'Turkish': 'Posta kodu',
  'Dutch': 'Postcode',
  'Swedish': 'Postnummer',
  'Norwegian': 'Postnummer',
  'Finnish': 'Postinumero',
  'Greek': 'Ταχυδρομικός κώδικας',
  'Thai': 'รหัสไปรษณีย์',
};

// descrption

const Map<String, String> contactToExporterTranslations = {
  'Hindi': 'निर्यातकर्ता से संपर्क करें',
  'Bengali': 'রপ্তানিকারকে যোগাযোগ করুন',
  'Telugu': 'ఎగుమతి యొక్క సంప్రదించండి',
  'Marathi': 'निर्यातकाशी संपर्क साधा',
  'Tamil': 'ஏற்றுத்தாராக்களுடன் தொடர்பு கொள்ளவும்',
  'Urdu': 'براٹر سے رابطہ کریں',
  'Gujarati': 'નિર્યાતક સાથે સંપર્ક કરો',
  'Malayalam': 'പരിപാലകനുമായി ബന്ധപ്പെടുക',
  'Kannada': 'ರಫ್ತಾದಾರನಿಗೆ ಸಂಪರ್ಕಿಸಿ',
  'Odia': 'ନିର୍ୟାତକରେ ସଂପର୍କ କରନ୍ତୁ',
  'Punjabi': 'ਨਿਰਯਾਤਕ ਨਾਲ ਸੰਪਰਕ ਕਰੋ',
  'Assamese': 'রফতাৰ প্ৰদাতালৈ যোগাযোগ কৰক',
  'Nepali': 'निर्यातकर्तासँग सम्पर्क गर्नुहोस्',
  'English': 'Contact to Exporter',
  'Spanish': 'Contactar con el exportador',
  'French': 'Contacter l’exportateur',
  'German': 'Mit dem Exporteur Kontakt aufnehmen',
  'Italian': 'Contattare l\'esportatore',
  'Portuguese': 'Contatar o exportador',
  'Russian': 'Связаться с экспортером',
  'Chinese': '联系出口商',
  'Japanese': '輸出業者に連絡',
  'Korean': '수출업자에게 연락하기',
  'Turkish': 'İhracatçıya irtibat',
  'Dutch': 'Contact opnemen met de exporteur',
  'Swedish': 'Kontakta exportören',
  'Norwegian': 'Kontakt eksportøren',
  'Finnish': 'Ota yhteyttä viejään',
  'Greek': 'Επικοινωνία με τον εξαγωγέα',
  'Thai': 'ติดต่อผู้ส่งออก',
};

const Map<String, String> addToCartTranslations = {
  'Hindi': 'कार्ट में डालें',
  'Bengali': 'কার্টে যোগ করুন',
  'Telugu': 'కార్ట్‌కు జోడించండి',
  'Marathi': 'कार्टमध्ये जोडा',
  'Tamil': 'கார்ட்டில் சேர்க்க',
  'Urdu': 'کارٹ میں شامل کریں',
  'Gujarati': 'કાર્ટમાં ઉમેરો',
  'Malayalam': 'കാർട്ടിലേക്ക് ചേർക്കുക',
  'Kannada': 'ಕಾರ್ಟ್‌ಗೆ ಸೇರಿಸಿ',
  'Odia': 'କାର୍ଟରେ ଯୋଗ କରନ୍ତୁ',
  'Punjabi': 'ਕਾਰਟ ਵਿੱਚ ਸ਼ਾਮਲ ਕਰੋ',
  'Assamese': 'কাৰ্টত যোগ কৰক',
  'Nepali': 'कार्टमा थप्नुहोस्',
  'English': 'Add to Cart',
  'Spanish': 'Añadir al carrito',
  'French': 'Ajouter au panier',
  'German': 'In den Warenkorb legen',
  'Italian': 'Aggiungi al carrello',
  'Portuguese': 'Adicionar ao carrinho',
  'Russian': 'Добавить в корзину',
  'Chinese': '加入购物车',
  'Japanese': 'カートに追加',
  'Korean': '장바구니에 추가',
  'Turkish': 'Sepete ekle',
  'Dutch': 'Toevoegen aan winkelwagen',
  'Swedish': 'Lägg till i varukorgen',
  'Norwegian': 'Legg til i handlekurven',
  'Finnish': 'Lisää ostoskoriin',
  'Greek': 'Προσθήκη στο καλάθι',
  'Thai': 'เพิ่มลงในตะกร้า',
};

const Map<String, String> quantityTranslations = {
  'Hindi': 'मात्रा',
  'Bengali': 'পরিমাণ',
  'Telugu': 'పరిమాణం',
  'Marathi': 'प्रमाण',
  'Tamil': 'அளவு',
  'Urdu': 'مقدار',
  'Gujarati': 'પ્રમાણ',
  'Malayalam': 'അളവ്',
  'Kannada': 'ಪ್ರಮಾಣ',
  'Odia': 'ପ୍ରମାଣ',
  'Punjabi': 'ਮਾਤਰਾ',
  'Assamese': 'পৰিমাণ',
  'Nepali': 'मात्रा',
  'English': 'Quantity',
  'Spanish': 'Cantidad',
  'French': 'Quantité',
  'German': 'Menge',
  'Italian': 'Quantità',
  'Portuguese': 'Quantidade',
  'Russian': 'Количество',
  'Chinese': '数量',
  'Japanese': '数量',
  'Korean': '수량',
  'Turkish': 'Miktar',
  'Dutch': 'Hoeveelheid',
  'Swedish': 'Mängd',
  'Norwegian': 'Antall',
  'Finnish': 'Määrä',
  'Greek': 'Ποσότητα',
  'Thai': 'ปริมาณ',
};

//your cart

const Map<String, String> yourCartTranslations = {
  'Hindi': 'आपका कार्ट',
  'Bengali': 'আপনার কার্ট',
  'Telugu': 'మీ కార్ట్',
  'Marathi': 'तुमचा कार्ट',
  'Tamil': 'உங்கள் கார்ட்',
  'Urdu': 'آپ کی ٹوکری',
  'Gujarati': 'તમારું કાર્ટ',
  'Malayalam': 'നിങ്ങളുടെ കാർട്ട്',
  'Kannada': 'ನಿಮ್ಮ ಕಾರ್ಟ್',
  'Odia': 'ଆପଣଙ୍କ କାର୍ଟ',
  'Punjabi': 'ਤੁਹਾਡਾ ਕਾਰਟ',
  'Assamese': 'আপোনাৰ কাৰ্ট',
  'Nepali': 'तपाईंको कार्ट',
  'English': 'Your Cart',
  'Spanish': 'Tu carrito',
  'French': 'Votre panier',
  'German': 'Ihr Warenkorb',
  'Italian': 'Il tuo carrello',
  'Portuguese': 'Seu carrinho',
  'Russian': 'Ваша корзина',
  'Chinese': '您的购物车',
  'Japanese': 'カート',
  'Korean': '장바구니',
  'Turkish': 'Sepetiniz',
  'Dutch': 'Uw winkelwagen',
  'Swedish': 'Din varukorg',
  'Norwegian': 'Handlekurven din',
  'Finnish': 'Ostoskorisi',
  'Greek': 'Το καλάθι σας',
  'Thai': 'ตะกร้าของคุณ',
};

const Map<String, String> itemTranslations = {
  'Hindi': 'आइटम',
  'Bengali': 'আইটেম',
  'Telugu': 'అంశం',
  'Marathi': 'आयटम',
  'Tamil': 'பொருள்',
  'Urdu': 'آئٹم',
  'Gujarati': 'આઇટમ',
  'Malayalam': 'ഇനം',
  'Kannada': 'ಐಟಮ್',
  'Odia': 'ଆୟତମ',
  'Punjabi': 'ਆਇਟਮ',
  'Assamese': 'আইটেম',
  'Nepali': 'वस्तु',
  'English': 'Item',
  'Spanish': 'Artículo',
  'French': 'Article',
  'German': 'Artikel',
  'Italian': 'Articolo',
  'Portuguese': 'Item',
  'Russian': 'Товар',
  'Chinese': '物品',
  'Japanese': 'アイテム',
  'Korean': '물건',
  'Turkish': 'Ürün',
  'Dutch': 'Item',
  'Swedish': 'Artikel',
  'Norwegian': 'Vare',
  'Finnish': 'Tuote',
  'Greek': 'Στοιχείο',
  'Thai': 'สิ่งของ',
};

const Map<String, String> totalTranslations = {
  'Hindi': 'कुल',
  'Bengali': 'মোট',
  'Telugu': 'మొత్తం',
  'Marathi': 'एकूण',
  'Tamil': 'மொத்தம்',
  'Urdu': 'کل',
  'Gujarati': 'કુલ',
  'Malayalam': 'മൊത്തം',
  'Kannada': 'ಒಟ್ಟು',
  'Odia': 'ମୋଟ',
  'Punjabi': 'ਕੁੱਲ',
  'Assamese': 'মোট',
  'Nepali': 'कुल',
  'English': 'Total',
  'Spanish': 'Total',
  'French': 'Total',
  'German': 'Gesamt',
  'Italian': 'Totale',
  'Portuguese': 'Total',
  'Russian': 'Итого',
  'Chinese': '总计',
  'Japanese': '合計',
  'Korean': '총계',
  'Turkish': 'Toplam',
  'Dutch': 'Totaal',
  'Swedish': 'Totalt',
  'Norwegian': 'Totalt',
  'Finnish': 'Yhteensä',
  'Greek': 'Σύνολο',
  'Thai': 'รวม',
};

const Map<String, String> doPaymentTranslations = {
  'Hindi': 'भुगतान करें',
  'Bengali': 'পেমেন্ট করুন',
  'Telugu': 'చెల్లించండి',
  'Marathi': 'पेमेंट करा',
  'Tamil': 'கட்டணம் செய்யவும்',
  'Urdu': 'ادائیگی کریں',
  'Gujarati': 'ચુકવો',
  'Malayalam': 'പേയ്‌മെന്റ് ചെയ്യുക',
  'Kannada': 'ಪಾವತಿ ಮಾಡಿ',
  'Odia': 'ପେମେଣ୍ଟ କରନ୍ତୁ',
  'Punjabi': 'ਭੁਗਤਾਨ ਕਰੋ',
  'Assamese': 'পেমেণ্ট কৰক',
  'Nepali': 'भुक्तान गर्नुहोस्',
  'English': 'Do Payment',
  'Spanish': 'Hacer el pago',
  'French': 'Effectuer le paiement',
  'German': 'Zahlung durchführen',
  'Italian': 'Effettuare il pagamento',
  'Portuguese': 'Fazer o pagamento',
  'Russian': 'Оплатить',
  'Chinese': '进行付款',
  'Japanese': '支払いをする',
  'Korean': '결제하기',
  'Turkish': 'Ödeme yap',
  'Dutch': 'Betaling uitvoeren',
  'Swedish': 'Gör betalning',
  'Norwegian': 'Utfør betaling',
  'Finnish': 'Tee maksu',
  'Greek': 'Κάντε πληρωμή',
  'Thai': 'ทำการชำระเงิน',
};

const Map<String, String> checkOutTranslations = {
  'Hindi': 'चेक आउट',
  'Bengali': 'চেক আউট',
  'Telugu': 'చెక్ అవుట్',
  'Marathi': 'चेक आउट',
  'Tamil': 'சரிபார்க்கவும்',
  'Urdu': 'چیک آؤٹ',
  'Gujarati': 'ચેક આઉટ',
  'Malayalam': 'ചെക്കൗട്ട്',
  'Kannada': 'ಚೆಕ್ ಔಟ್',
  'Odia': 'ଚେକ୍ ଆଉଟ୍',
  'Punjabi': 'ਚੈੱਕ ਆਉਟ',
  'Assamese': 'চেক আউট',
  'Nepali': 'चेक आउट',
  'English': 'Check Out',
  'Spanish': 'Pagar',
  'French': 'Passer à la caisse',
  'German': 'Auschecken',
  'Italian': 'Pagare',
  'Portuguese': 'Finalizar compra',
  'Russian': 'Оформить заказ',
  'Chinese': '结账',
  'Japanese': 'チェックアウト',
  'Korean': '체크아웃',
  'Turkish': 'Çıkış yap',
  'Dutch': 'Afrekenen',
  'Swedish': 'Gå till kassan',
  'Norwegian': 'Sjekk ut',
  'Finnish': 'Tarkista',
  'Greek': 'Ολοκλήρωση αγοράς',
  'Thai': 'ชำระเงิน',
};

//checkout screen

const Map<String, String> addressTranslations = {
  'Hindi': 'पता',
  'Bengali': 'ঠিকানা',
  'Telugu': 'చిరునామా',
  'Marathi': 'पत्ता',
  'Tamil': 'முகவரி',
  'Urdu': 'پتہ',
  'Gujarati': 'સરનામું',
  'Malayalam': 'വിലാസം',
  'Kannada': 'ವಿಳಾಸ',
  'Odia': 'ସରନାମୁଁ',
  'Punjabi': 'ਪਤਾ',
  'Assamese': 'ঠিকানা',
  'Nepali': 'ठेगाना',
  'English': 'Address',
  'Spanish': 'Dirección',
  'French': 'Adresse',
  'German': 'Adresse',
  'Italian': 'Indirizzo',
  'Portuguese': 'Endereço',
  'Russian': 'Адрес',
  'Chinese': '地址',
  'Japanese': '住所',
  'Korean': '주소',
  'Turkish': 'Adres',
  'Dutch': 'Adres',
  'Swedish': 'Adress',
  'Norwegian': 'Adresse',
  'Finnish': 'Osoite',
  'Greek': 'Διεύθυνση',
  'Thai': 'ที่อยู่',
};

const Map<String, String> orderSummaryTranslations = {
  'Hindi': 'आदेश सारांश',
  'Bengali': 'অর্ডার সারাংশ',
  'Telugu': 'ఆర్డర్ సారాంశం',
  'Marathi': 'क्रम संक्षेप',
  'Tamil': 'ஆர்டர் சுருக்கம்',
  'Urdu': 'آرڈر خلاصہ',
  'Gujarati': 'ઓર્ડર સારાંશ',
  'Malayalam': 'ഓർഡർ സംഗ്രഹം',
  'Kannada': 'ಆರ್ಡರ್ ಸಾರಾಂಶ',
  'Odia': 'ଅର୍ଡର୍ ସାରାଂଶ',
  'Punjabi': 'ਆਰਡਰ ਸੰਖੇਪ',
  'Assamese': 'অৰ্ডাৰ সংক্ষেপ',
  'Nepali': 'आदेश संक्षेप',
  'English': 'Order Summary',
  'Spanish': 'Resumen del pedido',
  'French': 'Résumé de la commande',
  'German': 'Bestellübersicht',
  'Italian': 'Riepilogo dell\'ordine',
  'Portuguese': 'Resumo do pedido',
  'Russian': 'Сводка заказа',
  'Chinese': '订单摘要',
  'Japanese': '注文の要約',
  'Korean': '주문 요약',
  'Turkish': 'Sipariş Özeti',
  'Dutch': 'Bestellingsoverzicht',
  'Swedish': 'Beställningsöversikt',
  'Norwegian': 'Ordresammendrag',
  'Finnish': 'Tilauksen yhteenveto',
  'Greek': 'Σύνοψη παραγγελίας',
  'Thai': 'สรุปคำสั่งซื้อ',
};

const Map<String, String> paymentTranslations = {
  'Hindi': 'भुगतान',
  'Bengali': 'পেমেন্ট',
  'Telugu': 'చెల్లింపు',
  'Marathi': 'पेमेंट',
  'Tamil': 'கட்டணம்',
  'Urdu': 'ادائیگی',
  'Gujarati': 'ચુકવો',
  'Malayalam': 'പേയ്മെന്റ്',
  'Kannada': 'ಪಾವತಿ',
  'Odia': 'ପେମେଣ୍ଟ',
  'Punjabi': 'ਭੁਗਤਾਨ',
  'Assamese': 'মোচন',
  'Nepali': 'भुक्तानी',
  'English': 'Payment',
  'Spanish': 'Pago',
  'French': 'Paiement',
  'German': 'Zahlung',
  'Italian': 'Pagamento',
  'Portuguese': 'Pagamento',
  'Russian': 'Оплата',
  'Chinese': '支付',
  'Japanese': '支払い',
  'Korean': '결제',
  'Turkish': 'Ödeme',
  'Dutch': 'Betaling',
  'Swedish': 'Betalning',
  'Norwegian': 'Betaling',
  'Finnish': 'Maksu',
  'Greek': 'Πληρωμή',
  'Thai': 'การชำระเงิน',
};

const Map<String, String> deliverHereTranslations = {
  'Hindi': 'यहाँ डिलीवर करें',
  'Bengali': 'এখানে ডেলিভার করুন',
  'Telugu': 'ఇక్కడ పంపండి',
  'Marathi': 'इथे वितरित करा',
  'Tamil': 'இங்கே விநியோகிக்கவும்',
  'Urdu': 'یہاں ڈلیور کریں',
  'Gujarati': 'અહીં પહોંચાડો',
  'Malayalam': 'ഇവിടെ വിതരിച്ചാലും',
  'Kannada': 'ಇಲ್ಲಿ ವಹಿಸಿ',
  'Odia': 'ଏଠାରେ ପଠାଇ ନିଯାଇ ଦିଅନ୍ତୁ',
  'Punjabi': 'ਇੱਥੇ ਪਹੁੰਚਾਓ',
  'Assamese': 'ইয়াত পৌঁছাওক',
  'Nepali': 'यहाँ पुर्याउनुहोस्',
  'English': 'DELIVER HERE',
  'Spanish': 'ENTREGAR AQUÍ',
  'French': 'LIVRER ICI',
  'German': 'HIER LIEFERN',
  'Italian': 'CONSEGNARE QUI',
  'Portuguese': 'ENTREGAR AQUI',
  'Russian': 'ДОСТАВИТЬ СЮДА',
  'Chinese': '送到这里',
  'Japanese': 'ここに配達',
  'Korean': '여기로 배송',
  'Turkish': 'BURAYA TESLİM ET',
  'Dutch': 'HIER BEZORGEN',
  'Swedish': 'LEVERERA HÄR',
  'Norwegian': 'LEVER HER',
  'Finnish': 'TOIMITA TÄHÄN',
  'Greek': 'ΠΑΡΑΔΩΣΤΕ ΕΔΩ',
  'Thai': 'ส่งมอบที่นี่',
};

const Map<String, String> fillAddressDetailsTranslations = {
  'Hindi': 'पता विवरण भरें',
  'Bengali': 'ঠিকানা বিবরণ পূরণ করুন',
  'Telugu': 'చిరునామా వివరాలను నమోదు చేయండి',
  'Marathi': 'पत्ता तपशील भरा',
  'Tamil': 'முகவரி விவரங்களை நிரப்பவும்',
  'Urdu': 'پتہ کی تفصیلات بھریں',
  'Gujarati': 'સરનામુંની વિગતો ભરો',
  'Malayalam': 'വിലാസ വിശദാംശങ്ങൾ പൂരിപ്പിക്കുക',
  'Kannada': 'ವಿಳಾಸ ವಿವರಗಳನ್ನು ನೀಡಿ',
  'Odia': 'ଠିକଣା ବିବରଣ ପୂର୍ଣ କରନ୍ତୁ',
  'Punjabi': 'ਐਡਰੈੱਸ ਵੇਰਵਾ ਭਰੋ',
  'Assamese': 'ঠিকানা বিবৰণ ভৰকৈ দিন',
  'Nepali': 'ठेगाना विवरण भर्नुहोस्',
  'English': 'Fill Address Details',
  'Spanish': 'Completar detalles de la dirección',
  'French': 'Remplir les détails de l\'adresse',
  'German': 'Adresse ausfüllen',
  'Italian': 'Compila i dettagli dell\'indirizzo',
  'Portuguese': 'Preencher detalhes do endereço',
  'Russian': 'Заполнить данные адреса',
  'Chinese': '填写地址详情',
  'Japanese': '住所の詳細を記入する',
  'Korean': '주소 세부 정보 입력',
  'Turkish': 'Adres detaylarını doldurun',
  'Dutch': 'Vul adresgegevens in',
  'Swedish': 'Fyll i adressdetaljer',
  'Norwegian': 'Fyll ut adressedetaljer',
  'Finnish': 'Täytä osoitetiedot',
  'Greek': 'Συμπληρώστε λεπτομέρειες διεύθυνσης',
  'Thai': 'กรอกข้อมูลที่อยู่',
};

const Map<String, String> payTranslations = {
  'Hindi': 'भुगतान करें',
  'Bengali': 'পে করুন',
  'Telugu': 'చెల్లించండి',
  'Marathi': 'पैसे द्या',
  'Tamil': 'கட்டணம் செலுத்து',
  'Urdu': 'ادا کریں',
  'Gujarati': 'ચુકવો',
  'Malayalam': 'പേയ്മെന്റ് ചെയ്യുക',
  'Kannada': 'ಪಾವತಿ ಮಾಡಿ',
  'Odia': 'ପେଇ କରନ୍ତୁ',
  'Punjabi': 'ਭੁਗਤਾਨ ਕਰੋ',
  'Assamese': 'পে কৰক',
  'Nepali': 'भुक्तान गर्नुहोस्',
  'English': 'Pay',
  'Spanish': 'Pagar',
  'French': 'Payer',
  'German': 'Bezahlen',
  'Italian': 'Pagare',
  'Portuguese': 'Pagar',
  'Russian': 'Оплатить',
  'Chinese': '支付',
  'Japanese': '支払う',
  'Korean': '지불하다',
  'Turkish': 'Öde',
  'Dutch': 'Betalen',
  'Swedish': 'Betala',
  'Norwegian': 'Betal',
  'Finnish': 'Maksaa',
  'Greek': 'Πληρώστε',
  'Thai': 'จ่าย',
};

// my orders

const Map<String, String> noOrdersFoundTranslations = {
  'Hindi': 'कोई आदेश नहीं मिला',
  'Bengali': 'কোনো আদেশ পাওয়া যায়নি',
  'Telugu': 'ఎవరూ ఆర్డర్లు కనబడలేదు',
  'Marathi': 'कोणतेही ऑर्डर सापडलेले नाहीत',
  'Tamil': 'ஆர்டர்கள் கிடைக்கவில்லை',
  'Urdu': 'کوئی آرڈر نہیں ملا',
  'Gujarati': 'કોઈ ઓર્ડર મળ્યો નથી',
  'Malayalam': 'ഒന്നും ആർഡർ കണ്ടെത്തിയില്ല',
  'Kannada': 'ಯಾವ ಆರ್ಡರ್ಗಳೂ ಕಾಣಲಿಲ್ಲ',
  'Odia': 'କୌଣସି ଆର୍ଡର୍ ପାଇଁ ଖୋଜ ହେଇ ନାହିଁ',
  'Punjabi': 'ਕੋਈ ਆਰਡਰ ਨਹੀਂ ਲੱਭਿਆ',
  'Assamese': 'কোনো অৰ্ডাৰ পোৱা নাই',
  'Nepali': 'कुनै आदेश फेला परेन',
  'English': 'No orders found',
  'Spanish': 'No se encontraron pedidos',
  'French': 'Aucune commande trouvée',
  'German': 'Keine Bestellungen gefunden',
  'Italian': 'Nessun ordine trovato',
  'Portuguese': 'Nenhum pedido encontrado',
  'Russian': 'Заказов не найдено',
  'Chinese': '未找到订单',
  'Japanese': '注文が見つかりませんでした',
  'Korean': '주문이 없습니다',
  'Turkish': 'Hiç sipariş bulunamadı',
  'Dutch': 'Geen bestellingen gevonden',
  'Swedish': 'Inga ordrar hittades',
  'Norwegian': 'Ingen ordre funnet',
  'Finnish': 'Ei löydettyjä tilauksia',
  'Greek': 'Δεν βρέθηκαν παραγγελίες',
  'Thai': 'ไม่พบคำสั่งซื้อ',
};

//settings

const Map<String, String> changeLanguageTranslations = {
  'Hindi': 'भाषा बदलें',
  'Bengali': 'ভাষা পরিবর্তন করুন',
  'Telugu': 'భాషను మార్చు',
  'Marathi': 'भाषा बदला',
  'Tamil': 'மொழியை மாற்றவும்',
  'Urdu': 'زبان تبدیل کریں',
  'Gujarati': 'ભાષા બદલો',
  'Malayalam': 'ഭാഷ മാറ്റുക',
  'Kannada': 'ಭಾಷೆ ಬದಲಿಸಿ',
  'Odia': 'ଭାଷା ପରିବର୍ତ୍ତନ କରନ୍ତୁ',
  'Punjabi': 'ਭਾਸ਼ਾ ਬਦਲੋ',
  'Assamese': 'ভাষা সলনি কৰক',
  'Nepali': 'भाषा परिवर्तन गर्नुहोस्',
  'English': 'Change Language',
  'Spanish': 'Cambiar idioma',
  'French': 'Changer de langue',
  'German': 'Sprache ändern',
  'Italian': 'Cambia lingua',
  'Portuguese': 'Alterar idioma',
  'Russian': 'Изменить язык',
  'Chinese': '更改语言',
  'Japanese': '言語を変更する',
  'Korean': '언어 변경',
  'Turkish': 'Dili değiştir',
  'Dutch': 'Taal wijzigen',
  'Swedish': 'Byt språk',
  'Norwegian': 'Endre språk',
  'Finnish': 'Vaihda kieltä',
  'Greek': 'Αλλαγή γλώσσας',
  'Thai': 'เปลี่ยนภาษา',
};
const Map<String, String> savedAddressTranslations = {
  'Hindi': 'सहेजा गया पता',
  'Bengali': 'সংরক্ষিত ঠিকানা',
  'Telugu': 'సేవ్ చేసిన చిరునామా',
  'Marathi': 'सेव्ह केला पत्ता',
  'Tamil': 'சேமிக்கப்பட்ட முகவரி',
  'Urdu': 'محفوظ کیا گیا پتہ',
  'Gujarati': 'સાચવેલું સરનામું',
  'Malayalam': 'സേവ് ചെയ്ത വിലാസം',
  'Kannada': 'ಉಳಿಸಲಾದ ವಿಳಾಸ',
  'Odia': 'ସେଭ୍ କରାଯାଇଛି ଠିକଣା',
  'Punjabi': 'ਸੰਭਾਲਿਆ ਗਿਆ ਪਤਾ',
  'Assamese': 'সংরক্ষিত কৰা ঠিকনা',
  'Nepali': 'संचित गरिएको ठेगाना',
  'English': 'Saved Address',
  'Spanish': 'Dirección guardada',
  'French': 'Adresse enregistrée',
  'German': 'Gespeicherte Adresse',
  'Italian': 'Indirizzo salvato',
  'Portuguese': 'Endereço salvo',
  'Russian': 'Сохраненный адрес',
  'Chinese': '已保存地址',
  'Japanese': '保存された住所',
  'Korean': '저장된 주소',
  'Turkish': 'Kayıtlı Adres',
  'Dutch': 'Opgeslagen adres',
  'Swedish': 'Sparad adress',
  'Norwegian': 'Lagret adresse',
  'Finnish': 'Tallennettu osoite',
  'Greek': 'Αποθηκευμένη διεύθυνση',
  'Thai': 'ที่อยู่ที่บันทึกไว้',
};

// logout

const Map<String, String> signOutTranslations = {
  'Hindi': 'साइन आउट करें',
  'Bengali': 'সাইন আউট করুন',
  'Telugu': 'సైన్ అవుట్ చేయండి',
  'Marathi': 'साइन आउट करा',
  'Tamil': 'வெளியேறு',
  'Urdu': 'باہر نکلیں',
  'Gujarati': 'સાઇન આઉટ કરો',
  'Malayalam': 'സൈൻ ഔട്ട്',
  'Kannada': 'ಹೊರಗಿನಿ',
  'Odia': 'ସାଇନ୍ ଆଉଟ୍ କରନ୍ତୁ',
  'Punjabi': 'ਸਾਈਨ ਆਉਟ ਕਰੋ',
  'Assamese': 'ছাইন আউট কৰক',
  'Nepali': 'साइन आउट गर्नुहोस्',
  'English': 'Sign Out',
  'Spanish': 'Cerrar sesión',
  'French': 'Se déconnecter',
  'German': 'Abmelden',
  'Italian': 'Esci',
  'Portuguese': 'Sair',
  'Russian': 'Выйти',
  'Chinese': '登出',
  'Japanese': 'サインアウト',
  'Korean': '로그아웃',
  'Turkish': 'Çıkış yap',
  'Dutch': 'Afmelden',
  'Swedish': 'Logga ut',
  'Norwegian': 'Logg ut',
  'Finnish': 'Kirjaudu ulos',
  'Greek': 'Αποσύνδεση',
  'Thai': 'ออกจากระบบ',
};

const Map<String, String> cancelTranslations = {
  'Hindi': 'रद्द करें',
  'Bengali': 'বাতিল করুন',
  'Telugu': 'రద్దు చేయండి',
  'Marathi': 'रद्द करा',
  'Tamil': 'ரத்து செய்',
  'Urdu': 'منسوخ کریں',
  'Gujarati': 'રદ કરો',
  'Malayalam': 'റദ്ദാക്കുക',
  'Kannada': 'ರದ್ದು ಮಾಡಿ',
  'Odia': 'ରଦ୍ଦ କର',
  'Punjabi': 'ਰੱਦ ਕਰੋ',
  'Assamese': 'বাতিল কৰক',
  'Nepali': 'रद्द गर्नुहोस्',
  'English': 'Cancel',
  'Spanish': 'Cancelar',
  'French': 'Annuler',
  'German': 'Abbrechen',
  'Italian': 'Annulla',
  'Portuguese': 'Cancelar',
  'Russian': 'Отменить',
  'Chinese': '取消',
  'Japanese': 'キャンセル',
  'Korean': '취소',
  'Turkish': 'İptal',
  'Dutch': 'Annuleren',
  'Swedish': 'Avbryt',
  'Norwegian': 'Avbryt',
  'Finnish': 'Peruuta',
  'Greek': 'Ακύρωση',
  'Thai': 'ยกเลิก',
};

const Map<String, String> signOutConfirmationTranslations = {
  'Hindi': 'क्या आप वाकई साइन आउट करना चाहते हैं?',
  'Bengali': 'আপনি কি সত্যিই সাইন আউট করতে চান?',
  'Telugu': 'మీరు నిజముగా సైన్ అవుతున్నారా?',
  'Marathi': 'तुम्हाला खरंतर साइन आउट करायचंय का?',
  'Tamil': 'நீங்கள் உண்மையில் வெளியேற விரும்புகிறீர்களா?',
  'Urdu': 'کیا آپ واقعی بیرون نکلنا چاہتے ہیں؟',
  'Gujarati': 'શું તમે ખરેખર બહાર નીકળવા માંગો છો?',
  'Malayalam': 'നിങ്ങൾ വാസ്തവത്തിൽ പുറത്തേക്കുക വരുന്നുണ്ടോ?',
  'Kannada': 'ನೀವು ನಿಜವಾಗಿಯೇ ಹೊರಹೋಗಬಯಸುತ್ತೀರಾ?',
  'Odia': 'ଆପଣ ବାହାର ଯାଇବା ଚାହୁଁଛନ୍ତି ନାହିଁ?',
  'Punjabi': 'ਕੀ ਤੁਸੀਂ ਵਾਕਈ ਬਾਹਰ ਜਾਣਾ ਚਾਹੁੰਦੇ ਹੋ?',
  'Assamese': 'আপুনি কি সত্যিই বাহিৰ যাত বিচাৰে?',
  'Nepali': 'के तपाईं वास्तवमा बाहिर निस्कन चाहानुहुन्छ?',
  'English': 'Do you really want to sign out?',
  'Spanish': '¿Realmente quieres cerrar sesión?',
  'French': 'Voulez-vous vraiment vous déconnecter ?',
  'German': 'Möchten Sie sich wirklich abmelden?',
  'Italian': 'Vuoi davvero disconnetterti?',
  'Portuguese': 'Você realmente deseja sair?',
  'Russian': 'Вы действительно хотите выйти?',
  'Chinese': '您真的要退出吗？',
  'Japanese': '本当にサインアウトしますか？',
  'Korean': '정말로 로그아웃 하시겠습니까?',
  'Turkish': 'Gerçekten çıkış yapmak istiyor musunuz?',
  'Dutch': 'Wil je echt uitloggen?',
  'Swedish': 'Vill du verkligen logga ut?',
  'Norwegian': 'Vil du virkelig logge av?',
  'Finnish': 'Haluatko varmasti kirjautua ulos?',
  'Greek': 'Θέλετε πραγματικά να αποσυνδεθείτε;',
  'Thai': 'คุณต้องการออกจริงหรือไม่?',
};
