name: shop_app
description: Created by - Team Stealth Mode

# The following line prevents the package from being accidentally published to
# pub.dev using pub publish. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=3.0.2 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.3
  # if you are using latest flutter please update your flutter_svg package to ^0.18.*
  flutter_svg: ^2.0.7 # help us to use SVG in our app
  provider: ^6.0.5 # for State management
  flutter_native_splash: ^2.3.2
  arcore_flutter_plugin: ^0.1.0
  vector_math: ^2.1.4
  path_provider: ^2.1.1
  uuid: ^4.0.0
  lottie: ^2.6.0
  open_filex: ^4.3.2
  dialog_flowtter: ^0.3.3
  shared_preferences: ^2.2.1
  # order_tracker: ^0.0.2
  order_tracker_zen: ^1.0.0+4
  searchfield: ^0.9.0
  dropdown_button2: ^2.3.9
  accordion: ^2.6.0
  google_fonts: ^4.0.4
  otp_text_field: ^1.1.3
  email_otp: ^2.0.1
  razorpay_flutter: ^1.3.5
  get: ^4.6.5
  firebase_core: ^2.24.2
  firebase_database: ^10.3.8
  rating_dialog: ^2.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter

# flutter_native_splash:
#   image: assets/app_logo.png
#   color: "#FFFFFF"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  generate: true
  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/icons/
    - assets/app_logo_svg.svg
    - assets/app_logo.png
    - assets/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins/Poppins-Black.ttf
        - asset: assets/fonts/Poppins/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/Poppins/Poppins-Light.ttf
          weight: 300
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
