export default [
  {
    id: 1001,
    avatar: "https://i.pravatar.cc/300",
    productname: "painting",
    amount: 989.4,
    status: "Custom approved",
    date: "Mon Feb 03 2020 04:13:15   ",
    exp_id: 1001,
    exp_name: "Exporter name",
    exp_address: "address",
    exp_country: "India",
    exp_zipcode: 411001,
    exp_mobileno: 8273635546,
    exp_emailid: "abc@gmail.com",
    send_name: "Receiver name",
    send_address: "address",
    send_country: "India",
    send_zipcode: 411001,
    send_mobileno: 8273635546,
    send_emailid: "abc@gmail.com",
    payment: "NetBanking",
    dnkcenter_name: "dnk center name",
    dnkcenter_pincode: 411001,
    Volumetric_weight: 20,
  },
  {
    id: 1002,
    avatar: "https://i.pravatar.cc/300",
    productname: "Pottery",
    amount: 471.44,
    status: "PostOffice approved",
    date: "Fri Nov 29 2019 10:43:17   ",
    exp_id: 1001,
    exp_name: "Exporter name",
    exp_address: "address",
    exp_country: "India",
    exp_zipcode: 411001,
    exp_mobileno: 8273635546,
    exp_emailid: "abc@gmail.com",
    send_name: "Receiver name",
    send_address: "address",
    send_country: "India",
    send_zipcode: 411001,
    send_mobileno: 8273635546,
    send_emailid: "abc@gmail.com",
    dnkcenter_name: "dnk center name",
    dnkcenter_pincode: 411001,
    payment: "NetBanking",
    Volumetric_weight: 24,
  },
  {
    id: 1003,
    avatar: "https://i.pravatar.cc/300",
    productname: "painting",
    amount: 934.24,
    status: "Completed",
    date: "Fri Apr 03 2020 03:07:53   ",
    exp_id: 1001,
    exp_name: "Exporter name",
    exp_address: "address",
    exp_country: "India",
    exp_zipcode: 411001,
    exp_mobileno: 8273635546,
    exp_emailid: "abc@gmail.com",
    send_name: "Receiver name",
    send_address: "address",
    send_country: "India",
    send_zipcode: 411001,
    send_mobileno: 8273635546,
    send_emailid: "abc@gmail.com",
    payment: "NetBanking",
    dnkcenter_name: "dnk center name",
    dnkcenter_pincode: 411001,
    Volumetric_weight: 20,
  },
  {
    id: 1004,
    avatar: "https://i.pravatar.cc/300",
    productname: "Pottery",
    amount: 351.28,
    status: "Custom approved",
    date: "Fri Jun 21 2019 20:21:55   ",
    exp_id: 1001,
    exp_name: "Exporter name",
    exp_address: "address",
    exp_country: "India",
    exp_zipcode: 411001,
    exp_mobileno: 8273635546,
    exp_emailid: "abc@gmail.com",
    send_name: "Receiver name",
    send_address: "address",
    send_country: "India",
    send_zipcode: 411001,
    send_mobileno: 8273635546,
    send_emailid: "abc@gmail.com",
    payment: "NetBanking",
    dnkcenter_name: "dnk center name",
    dnkcenter_pincode: 411001,
    Volumetric_weight: 15
  },
  {
    id: 1005,
    avatar: "https://i.pravatar.cc/300",
    productname: "Pottery",
    amount: 355.3,
    status: "Completed",
    date: "Wed Aug 28 2019 15:31:43   ",
    exp_id: 1001,
    exp_name: "Exporter name",
    exp_address: "address",
    exp_country: "India",
    exp_zipcode: 411001,
    exp_mobileno: 8273635546,
    exp_emailid: "abc@gmail.com",
    send_name: "Receiver name",
    send_address: "address",
    send_country: "India",
    send_zipcode: 411001,
    send_mobileno: 8273635546,
    send_emailid: "abc@gmail.com",
    payment: "NetBanking",
    dnkcenter_name: "dnk center name",
    dnkcenter_pincode: 411001,
    Volumetric_weight: 20,
  },
  {
    id: 1006,
    avatar: "https://i.pravatar.cc/300",
    productname: "Pottery",
    amount: 525.42,
    status: "PostOffice approved",
    date: "Thu Jan 16 2020 09:53:33   ",
    exp_id: 1001,
    exp_name: "Exporter name",
    exp_address: "address",
    exp_country: "India",
    exp_zipcode: 411001,
    exp_mobileno: 8273635546,
    exp_emailid: "abc@gmail.com",
    send_name: "Receiver name",
    send_address: "address",
    send_country: "India",
    send_zipcode: 411001,
    send_mobileno: 8273635546,
    send_emailid: "abc@gmail.com",
    dnkcenter_name: "dnk center name",
    dnkcenter_pincode: 411001,
    payment: "NetBanking",
    Volumetric_weight: 20,
  },
  {
    id: 1007,
    avatar: "https://i.pravatar.cc/300",
    productname: "Pottery",
    amount: 414.99,
    status: "Custom detained",
    date: "Thu Jan 16 2020 09:53:33   ",
    exp_id: 1001,
    exp_name: "Exporter name",
    exp_address: "address",
    exp_country: "India",
    exp_zipcode: 411001,
    exp_mobileno: 8273635546,
    exp_emailid: "abc@gmail.com",
    send_name: "Receiver name",
    send_address: "address",
    send_country: "India",
    send_zipcode: 411001,
    send_mobileno: 8273635546,
    send_emailid: "abc@gmail.com",
    dnkcenter_name: "dnk center name",
    dnkcenter_pincode: 411001,
    payment: "NetBanking",
    Volumetric_weight: 28,
  },
  {
    id: 1008,
    avatar: "https://i.pravatar.cc/300",
    productname: "painting",
    amount: 488.0,
    status: "Dispatched",
    date: "Tue Jul 23 2019 00:24:44   ",
    exp_id: 1001,
    exp_name: "Exporter name",
    exp_address: "address",
    exp_country: "India",
    exp_zipcode: 411001,
    exp_mobileno: 8273635546,
    exp_emailid: "abc@gmail.com",
    send_name: "Receiver name",
    send_address: "address",
    send_country: "India",
    send_zipcode: 411001,
    send_mobileno: 8273635546,
    dnkcenter_name: "dnk center name",
    dnkcenter_pincode: 411001,
    send_emailid: "abc@gmail.com",
    payment: "NetBanking",
    Volumetric_weight: 27,
  },
  {
    id: 1009,
    avatar: "https://i.pravatar.cc/300",
    productname: "Pottery",
    amount: 502.69,
    status: "Dispatched",
    date: "Sat Feb 01 2020 12:57:03   ",
    exp_id: 1001,
    exp_name: "Exporter name",
    exp_address: "address",
    exp_country: "India",
    exp_zipcode: 411001,
    exp_mobileno: 8273635546,
    exp_emailid: "abc@gmail.com",
    send_name: "Receiver name",
    send_address: "address",
    send_country: "India",
    send_zipcode: 411001,
    send_mobileno: 8273635546,
    send_emailid: "abc@gmail.com",
    dnkcenter_name: "dnk center name",
    dnkcenter_pincode: 411001,
    payment: "NetBanking",
    Volumetric_weight: 24,
  },
  {
    id: 1010,
    avatar: "https://i.pravatar.cc/300",
    productname: "painting",
    amount: 911.09,
    status: "Dispatched",
    date: "Mon Sep 09 2019 12:03:25   ",
    exp_id: 1001,
    exp_name: "Exporter name",
    exp_address: "address",
    exp_country: "India",
    exp_zipcode: 411001,
    exp_mobileno: 8273635546,
    exp_emailid: "abc@gmail.com",
    send_name: "Receiver name",
    send_address: "address",
    send_country: "India",
    send_zipcode: 411001,
    send_mobileno: 8273635546,
    send_emailid: "abc@gmail.com",
    dnkcenter_name: "dnk center name",
    dnkcenter_pincode: 411001,
    payment: "NetBanking",
    Volumetric_weight: 26,
  },
  {
    id: 1011,
    avatar: "https://i.pravatar.cc/300",
    productname: "Pottery",
    amount: 656.94,
    status: "Completed",
    date: "Fri May 22 2020 17:46:12   ",
    exp_id: 1001,
    exp_name: "Exporter name",
    exp_address: "address",
    exp_country: "India",
    exp_zipcode: 411001,
    exp_mobileno: 8273635546,
    exp_emailid: "abc@gmail.com",
    send_name: "Receiver name",
    send_address: "address",
    send_country: "India",
    send_zipcode: 411001,
    send_mobileno: 8273635546,
    send_emailid: "abc@gmail.com",
    dnkcenter_name: "dnk center name",
    dnkcenter_pincode: 411001,
    payment: "NetBanking",
    Volumetric_weight: 24,
  },
  {
    id: 1012,
    avatar: "https://i.pravatar.cc/300",
    productname: "Pottery",
    amount: 120.78,
    status: "Completed",
    date: "Sun Nov 17 2019 11:59:50   ",
    exp_id: 1001,
    exp_name: "Exporter name",
    exp_address: "address",
    exp_country: "India",
    exp_zipcode: 411001,
    exp_mobileno: 8273635546,
    exp_emailid: "abc@gmail.com",
    send_name: "Receiver name",
    send_address: "address",
    send_country: "India",
    send_zipcode: 411001,
    send_mobileno: 8273635546,
    send_emailid: "abc@gmail.com",
    dnkcenter_name: "dnk center name",
    dnkcenter_pincode: 411001,
    payment: "NetBanking",
    Volumetric_weight: 24,
  },
  {
    id: 1013,
    avatar: "https://i.pravatar.cc/300",
    productname: "painting",
    amount: 824.12,
    status: "Completed",
    date: "Sun Sep 15 2019 06:43:56   ",
    exp_id: 1001,
    exp_name: "Exporter name",
    exp_address: "address",
    exp_country: "India",
    exp_zipcode: 411001,
    exp_mobileno: 8273635546,
    exp_emailid: "abc@gmail.com",
    send_name: "Receiver name",
    send_address: "address",
    send_country: "India",
    send_zipcode: 411001,
    send_mobileno: 8273635546,
    send_emailid: "abc@gmail.com",
    dnkcenter_name: "dnk center name",
    dnkcenter_pincode: 411001,
    payment: "NetBanking",
    Volumetric_weight: 30,
  },
  {
    id: 1014,
    avatar: "https://i.pravatar.cc/300",
    productname: "Pottery",
    amount: 172.97,
    status: "Completed",
    date: "Tue Dec 17 2019 01:46:37   ",
    exp_id: 1001,
    exp_name: "Exporter name",
    exp_address: "address",
    exp_country: "India",
    exp_zipcode: 411001,
    exp_mobileno: 8273635546,
    exp_emailid: "abc@gmail.com",
    send_name: "Receiver name",
    send_address: "address",
    send_country: "India",
    send_zipcode: 411001,
    send_mobileno: 8273635546,
    send_emailid: "abc@gmail.com",
    dnkcenter_name: "dnk center name",
    dnkcenter_pincode: 411001,
    payment: "NetBanking",
    Volumetric_weight: 20,
  },
  {
    id: 1015,
    avatar: "https://i.pravatar.cc/300",
    productname: "Pottery",
    amount: 515.74,
    status: "Completed",
    date: "Mon Jun 15 2020 04:04:32   ",
    exp_id: 1001,
    exp_name: "Exporter name",
    exp_address: "address",
    exp_country: "India",
    exp_zipcode: 411001,
    exp_mobileno: 8273635546,
    exp_emailid: "abc@gmail.com",
    send_name: "Receiver name",
    send_address: "address",
    send_country: "India",
    send_zipcode: 411001,
    send_mobileno: 8273635546,
    send_emailid: "abc@gmail.com",
    dnkcenter_name: "dnk center name",
    dnkcenter_pincode: 411001,
    payment: "NetBanking",
    Volumetric_weight: 24,
  },
];
